apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: location-model
  description: Entry point for AI Model & resources
spec:
  targets:
    - https://github.com/shrishs/rhdh-templates/blob/main/catalog-info.yaml